# The URL the site will be built for
base_url = "https://www.gabrielsantos.xyz/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Gabriel Santos Blog"

[markdown]

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "agola-dark"

[extra]
# Put all your custom variables here

links = [
    { title = "Mail", href = "mailto:cafezinh0@protonmail.com" },
    { title = "GitHub", href = "https://github.com/cafezinho21" },
   # { title = "LinkedIn", href = "https://linkedin.com" }
]
